app_port: 3000
app_image_name: "shevtsovnikita/sweather"
nginx_image_name: "sehvtsovnikita/sweather-reverse"
dockerhub_password: "{{ vault_dockerhub_password }}"
dockerhub_username: "{{ vault_dockerhub_username }}"